(add-to-list 'load-path "~/.emacs.d/el-get/session/lips")
(require 'session)
(defvar session-initialize '(de-saveplace session keys menus places))
(add-hook 'after-init-hook 'session-initialize)
;;(add-to-list 'load-path "~/.emacs.d/vendor/session/lisp")
;; (when (require 'session nil t)
;;   (setq session-initialize '(de-saveplace session keys menus places)
;;         session-globals-include '((kill-ring 50)
;;                                   (session-file-alist 500 t)
;;                                   (file-name-history 10000)))
;;   (add-hook 'after-init-hook 'session-initialize)
;;   (setq session-undo-check -1))
