(require 'mozc)  ; or (load-file "path-to-mozc.el")
(set-language-environment "Japanese")
(setq default-input-method "japanese-mozc")
(set-default-coding-systems 'utf-8)
(prefer-coding-system 'utf-8)
(set-terminal-coding-system 'utf-8)
(set-keyboard-coding-system 'utf-8)
(set-buffer-file-coding-system 'utf-8)
(setq default-buffer-file-coding-systems 'utf-8)
;(set-locale-environment 'ja_JP.UTF-8)

(provide 'config-mozc)
