(add-to-list 'load-path (expand-file-name "~/.emacs.d"))
(add-to-list 'load-path (expand-file-name "~/.emacs.d/cola-zero"))
(add-to-list 'load-path (expand-file-name "~/.emacs.d/site-lisp"))
(add-to-list 'load-path (expand-file-name "/usr/share/emacs/site-lisp"))

(setq custom-file (expand-file-name "~/.emacs.d/custom.el"))
(load custom-file 'noerror)

(require 'config-builtin)
(require 'config-keybind)
(require 'config-elpa)
;(require 'config-el-get)
;(require 'config-auto-async-byte-compile)
(require 'config-dired)
(require 'config-popwin)
(require 'config-flymake)
(require 'config-rvm)
(require 'config-ruby-electric)
(require 'config-ruby-mode)
(require 'config-rinari)
(require 'config-ri-emacs)
(require 'config-sass-mode)
(require 'config-tdd-bgcolor)
;(require 'config-calfw)
(require 'config-auto-complete)
(require 'config-c-eldoc)
(require 'config-cl-indent-patches)
(require 'config-slime)
(require 'config-ac-slime)
(require 'config-clojure-mode)
;(require 'config-e2wm)
(require 'config-evernote-mode)
(require 'config-gdb)
(require 'config-gist)
(require 'config-gtags)
(require 'config-haml-mode)
(require 'config-haskell-mode)
(require 'config-ghc-mod)
(require 'config-hi-line-mode)
;(require 'config-id-manager)
(require 'config-iswitchb)
(require 'config-magit)
(require 'config-markdown-mode)
(if (eq system-type 'darwin)
    (progn
      (require 'config-darwin)
      (require 'config-font)
      ))
(require 'config-migemo)
(require 'config-minibuf-isearch)
(require 'config-mode-line)
(require 'config-nognus)
(require 'config-org-ja)
(require 'config-org-mode)
;(require 'config-org-jekyll)
(require 'config-paredit)
(require 'config-po-mode)
(require 'config-rsense)
(require 'config-session)
(require 'config-tramp)
;(require 'config-windows)
(require 'config-yaml-mode)
(if (eq system-type 'gnu/linux)
    (progn
      (require 'config-mozc)
      )
    )
;(require 'config-evil)

(color-theme-sanityinc-solarized-light)
(set-frame-parameter (selected-frame) 'alpha '(85 70))
(add-to-list 'default-frame-alist '(alpha 85 70))
(setq visible-bell t)
