(add-to-list 'load-path "~/.emacs.d")
(add-to-list 'load-path "~/.emacs.d/vendor")

(setq custom-file "~/.emacs.d/cola-zero/custom.el")
(load custom-file 'noerror)

(load "cola-zero/defuns")
(load "cola-zero/font")
(load "cola-zero/builtin")
(load "cola-zero/keybind")
(load "cola-zero/hi-line-mode")
(load "cola-zero/mode-line")
(load "cola-zero/tramp")
(load "cola-zero/gdb")
(load "cola-zero/org")
(load "cola-zero/dired")
(load "cola-zero/ido")
(load "cola-zero/iswitchb")
;;(load "cola-zero/popwin")
(if (eq system-type 'darwin)
    (load "cola-zero/darwin"))

(vendor 'color-theme)
(vendor 'popwin)
(vendor 'elscreen)
(vendor 'elscreen-color-theme)
(vendor 'elscreen-dired)
(vendor 'elscreen-server)
(vendor 'scala-mode-auto)
(vendor 'haskell-mode)
(vendor 'ghc-mode)
(vendor 'magit)
(vendor 'e2wm)
(vendor 'c-eldoc)
(vendor 'auto-complete)
(vendor 'migemo)
(vendor 'ruby-mode)
(vendor 'rvm)
(vendor 'rsense)
(vendor 'rinari)
(vendor 'ri-emacs)
(vendor 'yaml-mode)
(vendor 'slime)