(add-to-list 'load-path "~/.emacs.d")
(add-to-list 'load-path "~/.emacs.d/vendor")

(setq custom-file "~/.emacs.d/cola-zero/custom.el")
(load custom-file 'noerror)

(load "cola-zero/defuns")
(load "cola-zero/font")
(load "cola-zero/builtin")
(load "cola-zero/keybind")
(load "cola-zero/hi-line-mode")
(load "cola-zero/mode-line")
(load "cola-zero/tramp")
(load "cola-zero/gdb")
(load "cola-zero/dired")
(load "cola-zero/ido")
(load "cola-zero/iswitchb")
(if (eq system-type 'darwin)
    (load "cola-zero/darwin"))

(vendor 'apel)
(vendor 'color-theme)
(vendor 'popwin)
(vendor 'elscreen)
(vendor 'elscreen-color-theme)
(vendor 'elscreen-dired)
(vendor 'elscreen-server)
(vendor 'scala-mode-auto)
(vendor 'haskell-mode)
(vendor 'ghc-mode)
(vendor 'magit)
(vendor 'gist)
(vendor 'e2wm)
(vendor 'c-eldoc)
(vendor 'auto-complete)
(vendor 'migemo)
(vendor 'ruby-mode)
(vendor 'ruby-block)
(vendor 'haml-mode)
(vendor 'sass-mode)
(vendor 'yari)
;(vendor 'rvm)
(vendor 'rsense)
(vendor 'rinari)
(vendor 'ri-emacs)
(vendor 'yaml-mode)
(vendor 'slime)
(vendor 'ac-slime)
(vendor 'cl-indent-patches)
(vendor 'clojure-mode)
(vendor 'deferred)
(vendor 'dict-osx)
(vendor 'po-mode)
(vendor 'ecb)
(vendor 'yasnippet)
(vendor 'markdown-mode)
(vendor 'org-mode)
(vendor 'org-jekyll)
(vendor 'org-mac-protocol)
;; (vendor 'deft)

;; (vendor 'bbdb)
;; (vendor 'gnus)

(vendor 'calfw)
(vendor 'emacs-id-manager)

(vendor 'flim)
(vendor 'semi)
(vendor 'emacs-w3m)
(vendor 'wanderlust)

(server-start)
